### ISSUE TITLE
Brakujące informacje o grupie

### ISSUE THREAD

**Issue by dominik-korsa** [cloud11665/vlo.rocks-api#1]
https://api.cld.sh/vlo/ttdata/2E
W niektórych przypadkach w odpowiedzi pole `group` jest puste, choć w edupage jest grupa
```jsonc
    [
      {
        "subject": "język angielski",
        "subject_short": "ang",
        "teacher": "A. Adamska",
        "classroom": "A4",
        "color": "#FF0000",
        "time_index": 3,
        "duration": 1,
        "group": "", // Brakująca grupa
        "date": "2022-03-31",
        "day_index": 3
      },
      {
        "subject": "język angielski",
        "subject_short": "ang",
        "teacher": "L. Oniszczuk",
        "classroom": "35",
        "color": "#9966FF",
        "time_index": 3,
        "duration": 1,
        "group": "", // Brakująca grupa
        "date": "2022-03-31",
        "day_index": 3
      },
      // (...)
    ]
```
![image](https://user-images.githubusercontent.com/29484605/161055633-ec74ecd3-ffe1-4e5e-b28d-65ce602d2765.png)

**Comment by cloud11665** [comment]
https://github.com/cloud11665/vlo.rocks-api/blob/64e8e991a02dd541ef6054f555ff54714799bbf1/functions.hy#L51-L52=

```hy
(cond [(= group "wychowanie fizyczne_dz") (return "wf dziewczyny")]
        [(= group "wychowanie fizyczne_ch") (return "wf chłopcy")]
       ;[(and (group.startswith "język") num) (return f"język {num}")]
        [(in "_" group) (return (prep-group (group.replace "_" " ")))]
        [(group.startswith "język niemiecki") (return "")]
        [(group.startswith "język angielski") (return "")]
        [num (return f"{(get group (slice (- (len num))))} {num}")]
        )
```

Znalazłem już problem. Zrobiłem to, jako szybki hack aby naprawić jakiegoś buga w [vlo.rocks](https://vlo.rocks)

**Comment by cloud11665** [comment]
jest też problem mały, bo edupage zwraca grupy językowe jako `"język angielski {n}"` albo `"język niemiecki {n}"` dla wszystkich języków. I teraz pytanie: czy zostawić grupy tak jak edupage je zwraca, czy jakoś próbować je przypisywać dla nauczycieli/sali?
Ten drugi sposób może się wywalić jak np. będzie jakieś zastępstwo / zmiana sali, czyli grupy by nie były stałe.
